#- command: 'sudo su'
- name: installing snmp and dependencies
  apt: name={{ item }}  update_cache=yes state=latest
  with_items:
     - snmp 
     - snmpd
  register: snmpd_status

- name: installing snmp MIB database dependencies
  apt: name={{ item }}  state=latest
  with_items:
     - snmp-mibs-downloader
    
- name: snmpd start
  service: name=snmpd state=started  
  when: snmpd_status|changed
