#- name: Install rpm
#  yum: pkg=rpm state=latest

- name: update all packages
  yum: name=* update_cache=yes

- name: creating directory
  file: "state=directory path={{project_root}}/{{packetbeat_name}}  owner=root group=root recurse=yes mode=0755"

- name: check if service exists
  stat: path=/etc/init.d/{{packetbeat_name}}
  register: pktbt_status

- name: install dependency service
  yum: pkg=libpcap  state=latest

- name: downloading in process
  get_url:
      url='https://download.elastic.co/beats/packetbeat/packetbeat-{{ packetbeat_version }}-x86_64.rpm'
      dest={{project_root}}/{{packetbeat_name}}/{{packetbeat_name}}-{{ packetbeat_version }}-x86_64.rpm
  register: get_pktbt
  when: not pktbt_status.stat.exists
  ignore_errors: true
  
- name: downloading is failed...now copying packetbeat from source
  copy: src=packetbeat-{{ packetbeat_version }}-x86_64.rpm  dest={{project_root}}/{{packetbeat_name}}
  when: get_pktbt|failed

- name: execute if packetbeat is not installed
  command: rpm -ivh "{{project_root}}/{{packetbeat_name}}/{{packetbeat_name}}-{{packetbeat_version}}-x86_64.rpm"
  when: not pktbt_status.stat.exists

