/usr/bin/tsdb fsck --fix  1n-ago  sum nova.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum nova.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum nova.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum neutron.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum neutron.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum neutron.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum cinder.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum cinder.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum cinder.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum glance.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum glance.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum glance.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum ceilometer.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum ceilometer.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum ceiloeter.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum heat.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum heat.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum heat.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum keystone.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum keystone.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum keystone.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum horizon.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum horizon.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum horizon.requests
/usr/bin/tsdb fsck --fix  1n-ago  sum swift.responsetime
/usr/bin/tsdb fsck --fix  1n-ago  sum swift.errors
/usr/bin/tsdb fsck --fix  1n-ago  sum swift.requests

